# Dependabot updates
# Docs: https://docs.github.com/es/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: deps
  # NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "@types/vscode"
    commit-message:
      prefix: deps
