/* eslint-disable @typescript-eslint/no-non-null-assertion */

// THIS FILE HAS BEEN GENERATED BY THE `syntax-to-token-pattern.py` GENERATOR
// DO NOT EDIT THIS FILE DIRECTLY! INSTEAD RUN THE PYTHON SCRIPT.
// ANY MANUAL EDITS MADE TO THIS FILE WILL BE OVERWRITTEN. YOU HAVE BEEN WARNED.
// Last generated: 01/06/2023 14:57:48 (UTC+0)

import * as AtlPatterns from "./atl-token-patterns.g";
import * as RenpyPatterns from "./renpy-token-patterns.g";
import * as PythonPatterns from "./python-token-patterns.g";

// Push all RenpyPatterns external includes
RenpyPatterns.keywords.patterns![1].patterns!.push(PythonPatterns.expression);
RenpyPatterns.constantPlaceholder.captures![2].patterns!.push(PythonPatterns.expression);
RenpyPatterns.pythonStatements.patterns![1].patterns!.push(PythonPatterns.python);
RenpyPatterns.pythonStatements.patterns![2].patterns!.splice(2, 0, PythonPatterns.expression);
RenpyPatterns.sayStatements.patterns![0].endCaptures![3].patterns!.push(PythonPatterns.functionArguments);
RenpyPatterns.sayStatements.patterns![1].endCaptures![3].patterns!.push(PythonPatterns.functionArguments);
RenpyPatterns.transform.patterns!.push(AtlPatterns.atl);
RenpyPatterns.image.patterns![0].patterns!.push(AtlPatterns.atl);
RenpyPatterns.show.patterns![0].patterns!.push(AtlPatterns.atl);
RenpyPatterns.scene.patterns![0].patterns!.push(AtlPatterns.atl);
RenpyPatterns.camera.patterns![0].patterns!.push(AtlPatterns.atl);
RenpyPatterns.screenDefName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
RenpyPatterns.screenSimpleExpression.patterns!.push(PythonPatterns.literal, PythonPatterns.memberAccess, PythonPatterns.illegalOperator, PythonPatterns.operator, PythonPatterns.curlyBraces, PythonPatterns.itemAccess, PythonPatterns.list, PythonPatterns.oddFunctionCall, PythonPatterns.roundBraces, PythonPatterns.functionCall, PythonPatterns.builtinFunctions, PythonPatterns.builtinTypes, PythonPatterns.builtinExceptions, PythonPatterns.magicNames, PythonPatterns.specialNames, PythonPatterns.illegalNames, PythonPatterns.specialVariables, PythonPatterns.ellipsis, PythonPatterns.punctuation, PythonPatterns.lineContinuation);
RenpyPatterns.screenText.patterns![0].patterns!.push(AtlPatterns.atl);
RenpyPatterns.screen.patterns![0].beginCaptures![3].patterns!.splice(1, 0, PythonPatterns.parameters);
RenpyPatterns.labelName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
RenpyPatterns.labelCall.patterns!.splice(0, 0, PythonPatterns.specialVariables);
RenpyPatterns.labelCall.patterns!.push(PythonPatterns.functionArguments);
RenpyPatterns.labelDefName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
RenpyPatterns.label.captures![2].patterns!.splice(1, 0, PythonPatterns.parameters);
RenpyPatterns.returnStatements.patterns!.push(PythonPatterns.expression);
RenpyPatterns.callJumpExpression.patterns!.push(PythonPatterns.expression);
RenpyPatterns.callPass.patterns!.push(PythonPatterns.functionArguments);
RenpyPatterns.menuOption.beginCaptures![3].patterns!.splice(0, 0, PythonPatterns.functionArguments);
RenpyPatterns.menuOption.beginCaptures![3].patterns![1].captures![2].patterns!.push(PythonPatterns.expressionBare);
RenpyPatterns.menuSet.captures![2].patterns!.push(PythonPatterns.expressionBare);
RenpyPatterns.menu.beginCaptures![3].patterns!.push(PythonPatterns.functionArguments);
RenpyPatterns.audioParams.patterns!.push(PythonPatterns.number);
RenpyPatterns.play.patterns![0].patterns!.push(PythonPatterns.expression);
RenpyPatterns.queue.patterns![0].patterns!.push(PythonPatterns.expression);
RenpyPatterns.stop.patterns![0].patterns!.push(PythonPatterns.number);

// Push all AtlPatterns external includes
AtlPatterns.atlSimpleExpression.patterns!.splice(0, 0, RenpyPatterns.expressions);
AtlPatterns.atlSimpleExpression.patterns!.push(PythonPatterns.literal, PythonPatterns.memberAccess, PythonPatterns.illegalOperator, PythonPatterns.operator, PythonPatterns.curlyBraces, PythonPatterns.itemAccess, PythonPatterns.list, PythonPatterns.oddFunctionCall, PythonPatterns.roundBraces, PythonPatterns.functionCall, PythonPatterns.builtinFunctions, PythonPatterns.builtinTypes, PythonPatterns.builtinExceptions, PythonPatterns.magicNames, PythonPatterns.specialNames, PythonPatterns.illegalNames, PythonPatterns.specialVariables, PythonPatterns.ellipsis, PythonPatterns.punctuation, PythonPatterns.lineContinuation);
AtlPatterns.atlExpression.patterns!.push(PythonPatterns.expression);
AtlPatterns.atlEventName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
AtlPatterns.atlEventDefName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
AtlPatterns.atlOn.beginCaptures![3].patterns!.push(RenpyPatterns.comments);
AtlPatterns.atlFunction.captures![2].patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);
AtlPatterns.atlWarperName.patterns!.splice(0, 0, PythonPatterns.builtinPossibleCallables);

// Push all PythonPatterns external includes
PythonPatterns.stringUnicodeGuts.patterns!.splice(0, 0, RenpyPatterns.stringsInterior);


export { AtlPatterns, RenpyPatterns, PythonPatterns };